source 'https://rubygems.org'

gem 'configatron', '~> 4.5.0'
gem 'curb', '~> 0.8.8'
gem 'httpi', '~> 2.4.0'
gem 'json', '~> 1.8.1'
gem 'net-ldap', '~> 0.11'
gem 'sinatra', '~> 1.4.6'
gem 'sinatra-contrib', '~> 1.4.2'
gem 'sinatra-param', '~> 1.4.0'
